#!/bin/bash
set -e

echo "=== UP Beauty — Test Environment Setup ==="
echo ""

# 1. Start local Supabase (Docker)
echo "[1/4] Starting Docker Supabase..."
supabase start

# 2. Wait for API to be ready
echo "[2/4] Waiting for Supabase API..."
until curl -s http://127.0.0.1:54321/rest/v1/ > /dev/null 2>&1; do
  sleep 1
done
echo "       API ready."

# 3. Extract keys from supabase status
echo "[3/4] Extracting local keys..."
ANON_KEY=$(supabase status 2>/dev/null | grep "anon key" | awk '{print $NF}')
SERVICE_KEY=$(supabase status 2>/dev/null | grep "service_role key" | awk '{print $NF}')

if [ -z "$SERVICE_KEY" ]; then
  echo "ERROR: Could not extract service_role key from supabase status"
  exit 1
fi

# 4. Generate .env.test
echo "[4/4] Generating .env.test..."
cat > .env.test << EOF
# Auto-generated by scripts/setup-test-env.sh
# Local Docker Supabase — safe for testing (NOT production)

NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
NEXT_PUBLIC_SITE_URL=http://localhost:3000

# E2E test config
E2E_SUPABASE_URL=http://127.0.0.1:54321
E2E_SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
E2E_ADMIN_EMAIL=test@admin.com
E2E_ADMIN_PASSWORD=Test1234A
EOF

# Create test admin user (ignore error if already exists)
echo ""
echo "Creating test admin user (test@admin.com)..."
curl -s -o /dev/null -X POST http://127.0.0.1:54321/auth/v1/admin/users \
  -H "apikey: ${SERVICE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{"email":"test@admin.com","password":"Test1234A","email_confirm":true}' \
  || true

echo ""
echo "=== Test environment ready ==="
echo ""
echo "Run tests:"
echo "  npm test              # Unit tests"
echo "  npm run test:e2e:local  # E2E tests (uses .env.test)"
echo "  npm run test:all      # Both"
echo ""
echo "When done:"
echo "  npm run supabase:stop"
